-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 13:22:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PROJECTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROJECTS` (
  `ProjectName` VARCHAR(45) NOT NULL,
  `isAchived` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ProjectName`),
  UNIQUE INDEX `ProjectID_UNIQUE` (`ProjectName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TASKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TASKS` (
  `TASKSid` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `ProjectID` VARCHAR(45) NOT NULL COMMENT 'Name of project ',
  `OutlineID` VARCHAR(45) NOT NULL,
  `ParentTask` VARCHAR(45) NULL DEFAULT NULL,
  `isCompleted` TINYINT(1) NOT NULL DEFAULT 0,
  `isTerminal` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`TASKSid`),
  INDEX `Parent_idx` (`ParentTask` ASC) VISIBLE,
  INDEX `PID_idx` (`ProjectID` ASC) VISIBLE,
  CONSTRAINT `PID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb`.`PROJECTS` (`ProjectName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Parent`
    FOREIGN KEY (`ParentTask`)
    REFERENCES `mydb`.`TASKS` (`TASKSid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEMBERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEMBERS` (
  `MEMDERSid` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Pid` VARCHAR(45) NULL,
  PRIMARY KEY (`MEMDERSid`),
  INDEX `PROJID_idx` (`Pid` ASC) VISIBLE,
  CONSTRAINT `PROJID`
    FOREIGN KEY (`Pid`)
    REFERENCES `mydb`.`PROJECTS` (`ProjectName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASSIGNMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASSIGNMENTS` (
  `Tid` VARCHAR(45) NOT NULL,
  `Mid` VARCHAR(45) NOT NULL,
  INDEX `tid_idx` (`Tid` ASC) VISIBLE,
  PRIMARY KEY (`Tid`, `Mid`),
  INDEX `mid_idx` (`Mid` ASC) VISIBLE,
  CONSTRAINT `tid`
    FOREIGN KEY (`Tid`)
    REFERENCES `mydb`.`TASKS` (`TASKSid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mid`
    FOREIGN KEY (`Mid`)
    REFERENCES `mydb`.`MEMBERS` (`MEMDERSid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
